# Generated by Django 5.1.1 on 2024-09-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WiSSA_App', '0003_rename_header_image_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='header_image',
        ),
    ]
