# Generated by Django 5.0.4 on 2024-09-29 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WiSSA_App', '0004_rename_image_post_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='news_image',
        ),
    ]
