# Generated by Django 5.0.4 on 2024-09-29 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WiSSA_App', '0009_alter_post_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='news_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/product/'),
        ),
    ]
